server:
  port: 6666
spring:
  application:
    name: back-boot
  mvc:
    static-path-pattern: /**
  redis:
    host: 10.4.82.184
    port: 31946
    database: 3
  session:
    redis:
      namespace: data:session
    store-type: redis
  ldap:
    urls: ldap://tds02.baidu.com:389
    base: DC=BAIDU,DC=COM
  rabbitmq:
    host: 10.4.82.184
    port: 30217
    username: guest
    password: guest
  elasticsearch:
    rest:
      uris: 10.4.82.184:30080
